### PR TITLE
IPC-373: Fix balances returned with bogus rpc

### LINKED ISSUE #373: wallet balances returns even if bogus RPC
### Issue type

Bug

### Have you reproduced the bug with the latest dev version?

Yes

### Version

dev

### Custom code

Yes

### OS platform and distribution

_No response_

### Describe the issue

`./bin/ipc-cli wallet balances` returns no error even if using a bad (non-existent) RPC in the config; it just returns 0 balances for every wallet. The expected behaviour would be to return an error.

### Repro steps

Run `./bin/ipc-cli wallet balances --subnet XXX --wallet-type evm` using a well-formed but bogus RPC endpoint in the ipc-cli config.

### Relevant log output

```shell
# Correct RPC
ubuntu@ip-172-26-12-88:~/ipc$ ./bin/ipc-cli wallet balances --subnet /r314159/t410fqypdmnt3tyfczkis6iobfgqq72yk4web4ytehdi --wallet-type evm
0x310c8812089ee8efce8b06302ecf58a5c0fe549b - Balance: 1.0
0xc3964d4b507cb3dc4f24a5f0962fd7339ea568a7 - Balance: 0.0
0x93ef94dc6bda3283263366e569b0a0ffda1677b7 - Balance: 1.0
0x5126aa09cde4d5d85fc080cc3c069a8098eb2e10 - Balance: 1.0
default-key - Balance: 0

# Bogus RPC
ubuntu@ip-172-26-12-88:~/ipc$ ./bin/ipc-cli wallet balances --subnet /r314159/t410fqypdmnt3tyfczkis6iobfgqq72yk4web4ytehdi --wallet-type evm
default-key - Balance: 0
0xc3964d4b507cb3dc4f24a5f0962fd7339ea568a7 - Balance: 0
0x5126aa09cde4d5d85fc080cc3c069a8098eb2e10 - Balance: 0
0x310c8812089ee8efce8b06302ecf58a5c0fe549b - Balance: 0
0x93ef94dc6bda3283263366e569b0a0ffda1677b7 - Balance: 0
```

### PR DESCRIPTION
**Pull request by adlrocha**
Fixes #373

### CODE REVIEW

File: ipc/cli/src/commands/wallet/balances.rs [hunk 1]
```diff
@@ -50,16 +49,19 @@ impl CommandLineHandler for WalletBalances {
...
-                    let (balance, addr) = r;
-                    if addr.to_string() != "default-key" {
-                        println!("{} - Balance: {}", addr.to_string(), balance);
-                        no_balance.retain(|a| a != addr);
+                for r in v.into_iter() {
+                    match r {
+                        Ok(i) => {
+                            let (balance, addr) = i;
+                            if addr.to_string() != "default-key" {
+                                println!("{} - Balance: {}", addr.to_string(), balance);
```
Comment (aakoshh) [inline ipc/cli/src/commands/wallet/balances.rs:57]: I know we talked about this, but `jsonline` would be a good output format IMO, as it would make it easy to do something with the result using `jq`. A human readable output format is a great option, but personally I think it's liberating to print out structured data an defer the responsibility of formatting to the consumer.

File: ipc/cli/src/commands/wallet/balances.rs [hunk 2]
```diff
@@ -50,16 +49,19 @@ impl CommandLineHandler for WalletBalances {
...
-                for r in v.into_iter().filter_map(|r| r.ok()) {
-                    let (balance, addr) = r;
-                    if addr.to_string() != "default-key" {
-                        println!("{} - Balance: {}", addr.to_string(), balance);
-                        no_balance.retain(|a| a != addr);
+                for r in v.into_iter() {
+                    match r {
+                        Ok(i) => {
+                            let (balance, addr) = i;
+                            if addr.to_string() != "default-key" {
```
Comment (aakoshh) [inline ipc/cli/src/commands/wallet/balances.rs:56]: What is this `"default-key"`?

File: ipc/cli/src/commands/wallet/balances.rs [hunk 3]
```diff
@@ -50,16 +49,19 @@ impl CommandLineHandler for WalletBalances {
...
+                                println!("{} - Balance: {}", addr.to_string(), balance);
+                            }
+                        }
+                        Err(e) => {
+                            return Err(e);
```
Comment (aakoshh) [inline ipc/cli/src/commands/wallet/balances.rs:61]: Okay so we went from ignoring errors with `.filter_map(|r| r.ok())` and printing 0 balance for them to printing the first few successful balances until we encounter an error, where we stop going down the list and return an overall failure. 

That seems a bit inconsistent, that depending on which of the N requests failed I see more or less results, compared to for example:
* Print all results if all of them succeeded or none if any of them failed
* Print all results as JSON regardless of error or failure, but if it failed then print eg.. `{addr: "...", error: "oh noes!"}`
* Print all the successful results first and then return an overall error if any failed

The all-or-nothing strategy can be achieved for example like so:

```rust
let v: Vec<(TokenAmount, &EthKeyAddress)> = join_all(r).await.collect::<anyhow::Result<Vec<_>>>()?;
```

File: ipc/cli/src/commands/wallet/balances.rs (hunk 1 above)
Comment (adlrocha) [reply ipc/cli/src/commands/wallet/balances.rs:57]: I kind of agree, but let's tackle this as a joint effort after LabWeek and let's track the final approach we want to follow here: https://github.com/consensus-shipyard/ipc/issues/365. So far depending on who is reviewing the PR they suggest one approach or the other :see_no_evil:

For this one specifically, this approach seems more readable for humans than returning a JSON.

File: ipc/cli/src/commands/wallet/balances.rs (hunk 2 above)
Comment (adlrocha) [reply ipc/cli/src/commands/wallet/balances.rs:56]: This is the internal key used by the wallet store to tag the address being used as the default one for the wallet.

File: ipc/cli/src/commands/wallet/balances.rs (hunk 3 above)
Comment (adlrocha) [reply ipc/cli/src/commands/wallet/balances.rs]: This one is a bit tricky, because there are errors for which all balances will fail with the same error (like RPC unavailable), and others that may be address-specific (like address not initialized on-chain). I agree that my approach may have not been the best because it was non-deterministic, so I decided to go with your suggestion of printing all of the balances that succeed, and then returning the errors (if any) at the end. That way if it this is a balance-wide error (like RPC) we return a single error, and if it is address-specific we print the balances and then the errors. Let me know what you think.

File: ipc/cli/src/commands/wallet/balances.rs (hunk 2 above)
Comment (aakoshh) [reply ipc/cli/src/commands/wallet/balances.rs:58]: It's strange to see that returned in the API :thinking: 
And why do we skip printing the balance? Aren't you interested in seeing the balance of your default (maybe only) address? In JSON this could be `{addr: "f410...", balance: 1.23, default: true}`

File: ipc/cli/src/commands/wallet/balances.rs (hunk 1 above)
Comment (aakoshh) [reply ipc/cli/src/commands/wallet/balances.rs:59]: I'm sure it is more readable, and I agree you can postpone it. I guess like `ls -lh` you could have a "human readable hint" but it could also end up being an overkill.

File: ipc/cli/src/commands/wallet/balances.rs [hunk 4]
```diff
@@ -50,15 +51,27 @@ impl CommandLineHandler for WalletBalances {
...
                 }
-                for addr in no_balance {
-                    println!("{} - Balance: 0", addr.to_string());
+
+                if !errors.is_empty() {
+                    let error = errors
+                        .into_iter()
+                        .fold(anyhow::anyhow!("Error fetching balances"), |acc, err| {
+                            acc.context(err)
+                        });
```
Comment (aakoshh) [inline ipc/cli/src/commands/wallet/balances.rs:73]: Nice

**Review by aakoshh — APPROVED** [review]

File: ipc/cli/src/commands/wallet/balances.rs (hunk 1 above)
Comment (adlrocha) [reply ipc/cli/src/commands/wallet/balances.rs:59]: ^ I like this idea of having a flag for human-readable v.s. computer-readable. Will track it in the issue :pray:

File: ipc/cli/src/commands/wallet/balances.rs (hunk 2 above)
Comment (jsoares) [reply ipc/cli/src/commands/wallet/balances.rs:58]: I believe the default still stands as its own entry, no? At least I still see my default address printed out.

**Review by jsoares — APPROVED** [review]
It seems to do the job, i.e. now it errors out in case of bad RPC and prints fine in case of good RPC.
