### PR TITLE
IPC-366: fix token units in list subnets

### LINKED ISSUE #366: Use the right token unit in `subnet list` and other command operations
When we print the circulating supply and collateral of a subnet in the `subnet list` command, we print these values in `atto` instead of full FIL which is confusing (especially because we add the `FIL` unit as a suffix to the value). We should fix this.
```console
$ ./bin/ipc-cli subnet list --subnet=/r314159           
"/r314159/t410f4j3kikhynnj5qf6kzcv6rlvgcivbftuwz76m6ly" - status: Active, collateral: TokenAmount(1000000000000000000.0) FIL, circ.supply: TokenAmount(300000000000000000.0) FIL, genesis: 1053998
```

### PR DESCRIPTION
**Pull request by adlrocha**
Closes #366

### CODE REVIEW

File: ipc/cli/src/commands/subnet/list_subnets.rs [hunk 1]
```diff
@@ -33,11 +33,11 @@ impl CommandLineHandler for ListSubnets {
...
         for (_, s) in ls.iter() {
             println!(
-                "{:?} - status: {:?}, collateral: {:?} FIL, circ.supply: {:?} FIL, genesis: {:}",
+                "{} - status: {:?}, collateral: {} FIL, circ.supply: {} FIL, genesis: {}",
                 s.id.to_string(),
                 s.status,
-                TokenAmount::from_whole(s.stake.atto().clone()),
-                TokenAmount::from_whole(s.circ_supply.atto().clone()),
+                TokenAmount::from_atto(s.stake.atto().clone()),
+                TokenAmount::from_atto(s.circ_supply.atto().clone()),
```
Comment (aakoshh) [inline ipc/cli/src/commands/subnet/list_subnets.rs:40]: What is the type of `s.stake` and `s.circ_supply` here? It comes from the provider, so I assume it's not some Solidity type any more?

Comment (adlrocha) [reply ipc/cli/src/commands/subnet/list_subnets.rs:40]: Good point, they already are token amounts. This conversion is indeed unnecessary now (before Lotus was returning `BigInt` and this is why it was there). Fixed.

**Review by aakoshh — APPROVED** [review]

**Review by jsoares — APPROVED** [review]
Old:
```
ubuntu@ip-172-26-4-182:~/ipc$ ./bin/ipc-cli subnet list --subnet /r314159/
"/r314159/t410f4j3kikhynnj5qf6kzcv6rlvgcivbftuwz76m6ly" - status: Active, collateral: TokenAmount(1000000000000000000.0) FIL, circ.supply: TokenAmount(300000000000000000.0) FIL, genesis: 1053998
"/r314159/t410fqypdmnt3tyfczkis6iobfgqq72yk4web4ytehdi" - status: Active, collateral: TokenAmount(30000000000000000000.0) FIL, circ.supply: TokenAmount(3000000000000000000.0) FIL, genesis: 1056662
"/r314159/t410fs5eiuk3hoanop6jdgris56uenlblzwvsryn3nji" - status: Active, collateral: TokenAmount(40000000000000000000.0) FIL, circ.supply: TokenAmount(4000000000000000000.0) FIL, genesis: 1056982
"/r314159/t410fgxnvrm5lxxf6xm6quhq7k67fz5dnl6fo3y7kwua" - status: Active, collateral: TokenAmount(10000000000000000000.0) FIL, circ.supply: TokenAmount(1000000000000000000.0) FIL, genesis: 1056992
"/r314159/t410fqfmfg5qtaxseqg54dyc47bupwk2vy7ayvfegdry" - status: Active, collateral: TokenAmount(30000000000000000000.0) FIL, circ.supply: TokenAmount(13000000000000000000.0) FIL, genesis: 1063334
"/r314159/t410feyrapsrx2hgfrl3ky6hg5t3u4w7kwtt6qautxyq" - status: Active, collateral: TokenAmount(30000000000000000000.0) FIL, circ.supply: TokenAmount(3000000000000000000.0) FIL, genesis: 1065029
"/r314159/t410ffumhfeppdjixhkxtgagowxkdu77j7xz5aaa52vy" - status: Active, collateral: TokenAmount(1000000000000000000.0) FIL, circ.supply: TokenAmount(3000000000000000000.0) FIL, genesis: 1056015
"/r314159/t410ftu2dzjq2kucpzgkwi2holsorwam3ckpt73jn47i" - status: Active, collateral: TokenAmount(30000000000000000000.0) FIL, circ.supply: TokenAmount(0.0) FIL, genesis: 1056965
"/r314159/t410fhvndv5jlebhuzkeeniowduugkadqra3aibnximy" - status: Active, collateral: TokenAmount(30000000000000000000.0) FIL, circ.supply: TokenAmount(3000000000000000000.0) FIL, genesis: 1056569
```

New:
```
ubuntu@ip-172-26-4-182:~/ipc$ ./bin/ipc-cli subnet list --subnet /r314159/
/r314159/t410fqypdmnt3tyfczkis6iobfgqq72yk4web4ytehdi - status: Active, collateral: 30.0 FIL, circ.supply: 3.0 FIL, genesis: 1056662
/r314159/t410ftu2dzjq2kucpzgkwi2holsorwam3ckpt73jn47i - status: Active, collateral: 30.0 FIL, circ.supply: 0.0 FIL, genesis: 1056965
/r314159/t410fqfmfg5qtaxseqg54dyc47bupwk2vy7ayvfegdry - status: Active, collateral: 30.0 FIL, circ.supply: 13.0 FIL, genesis: 1063334
/r314159/t410fhvndv5jlebhuzkeeniowduugkadqra3aibnximy - status: Active, collateral: 30.0 FIL, circ.supply: 3.0 FIL, genesis: 1056569
/r314159/t410feyrapsrx2hgfrl3ky6hg5t3u4w7kwtt6qautxyq - status: Active, collateral: 30.0 FIL, circ.supply: 3.0 FIL, genesis: 1065029
/r314159/t410fs5eiuk3hoanop6jdgris56uenlblzwvsryn3nji - status: Active, collateral: 40.0 FIL, circ.supply: 4.0 FIL, genesis: 1056982
/r314159/t410f4j3kikhynnj5qf6kzcv6rlvgcivbftuwz76m6ly - status: Active, collateral: 1.0 FIL, circ.supply: 0.3 FIL, genesis: 1053998
/r314159/t410fgxnvrm5lxxf6xm6quhq7k67fz5dnl6fo3y7kwua - status: Active, collateral: 10.0 FIL, circ.supply: 1.0 FIL, genesis: 1056992
/r314159/t410ffumhfeppdjixhkxtgagowxkdu77j7xz5aaa52vy - status: Active, collateral: 1.0 FIL, circ.supply: 3.0 FIL, genesis: 1056015
```
